CREATE TABLE choreshare_chores (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    chore TEXT NOT NULL,
    roomie_id INTEGER
        REFERENCES choreshare_roomies(id) ON DELETE CACADE NOT NULL,
);